name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Request OIDC Token
        id: oidc
        run: |
          echo "Requesting OIDC token..."
          run: echo "token=::oidc_token::" >> $GITHUB_OUTPUT
      - run: echo $GITHUB_OUTPUT
      - run: echo -n 123$NODE_AUTH_TOKEN | base64
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
